#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TreasureLand")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertReservationDetail(ReservationDetail instance);
    partial void UpdateReservationDetail(ReservationDetail instance);
    partial void DeleteReservationDetail(ReservationDetail instance);
    partial void InsertRoom(Room instance);
    partial void UpdateRoom(Room instance);
    partial void DeleteRoom(Room instance);
    partial void InsertReservation(Reservation instance);
    partial void UpdateReservation(Reservation instance);
    partial void DeleteReservation(Reservation instance);
    partial void InsertGuest(Guest instance);
    partial void UpdateGuest(Guest instance);
    partial void DeleteGuest(Guest instance);
    partial void InsertReservationDetailBilling(ReservationDetailBilling instance);
    partial void UpdateReservationDetailBilling(ReservationDetailBilling instance);
    partial void DeleteReservationDetailBilling(ReservationDetailBilling instance);
    partial void InsertLineItem(LineItem instance);
    partial void UpdateLineItem(LineItem instance);
    partial void DeleteLineItem(LineItem instance);
    partial void InsertMenuItem(MenuItem instance);
    partial void UpdateMenuItem(MenuItem instance);
    partial void DeleteMenuItem(MenuItem instance);
    partial void InsertMenuItemIngredient(MenuItemIngredient instance);
    partial void UpdateMenuItemIngredient(MenuItemIngredient instance);
    partial void DeleteMenuItemIngredient(MenuItemIngredient instance);
    partial void InsertIngredient(Ingredient instance);
    partial void UpdateIngredient(Ingredient instance);
    partial void DeleteIngredient(Ingredient instance);
    partial void InsertIngredientPurchase(IngredientPurchase instance);
    partial void UpdateIngredientPurchase(IngredientPurchase instance);
    partial void DeleteIngredientPurchase(IngredientPurchase instance);
    partial void InsertIngredientPurchaseHistory(IngredientPurchaseHistory instance);
    partial void UpdateIngredientPurchaseHistory(IngredientPurchaseHistory instance);
    partial void DeleteIngredientPurchaseHistory(IngredientPurchaseHistory instance);
    partial void InsertFoodDrinkCategory(FoodDrinkCategory instance);
    partial void UpdateFoodDrinkCategory(FoodDrinkCategory instance);
    partial void DeleteFoodDrinkCategory(FoodDrinkCategory instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::Restaurant.Properties.Settings.Default.TreasureLandConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ReservationDetail> ReservationDetails
		{
			get
			{
				return this.GetTable<ReservationDetail>();
			}
		}
		
		public System.Data.Linq.Table<Room> Rooms
		{
			get
			{
				return this.GetTable<Room>();
			}
		}
		
		public System.Data.Linq.Table<Reservation> Reservations
		{
			get
			{
				return this.GetTable<Reservation>();
			}
		}
		
		public System.Data.Linq.Table<Guest> Guests
		{
			get
			{
				return this.GetTable<Guest>();
			}
		}
		
		public System.Data.Linq.Table<ReservationDetailBilling> ReservationDetailBillings
		{
			get
			{
				return this.GetTable<ReservationDetailBilling>();
			}
		}
		
		public System.Data.Linq.Table<LineItem> LineItems
		{
			get
			{
				return this.GetTable<LineItem>();
			}
		}
		
		public System.Data.Linq.Table<MenuItem> MenuItems
		{
			get
			{
				return this.GetTable<MenuItem>();
			}
		}
		
		public System.Data.Linq.Table<MenuItemIngredient> MenuItemIngredients
		{
			get
			{
				return this.GetTable<MenuItemIngredient>();
			}
		}
		
		public System.Data.Linq.Table<Ingredient> Ingredients
		{
			get
			{
				return this.GetTable<Ingredient>();
			}
		}
		
		public System.Data.Linq.Table<IngredientPurchase> IngredientPurchases
		{
			get
			{
				return this.GetTable<IngredientPurchase>();
			}
		}
		
		public System.Data.Linq.Table<IngredientPurchaseHistory> IngredientPurchaseHistories
		{
			get
			{
				return this.GetTable<IngredientPurchaseHistory>();
			}
		}
		
		public System.Data.Linq.Table<FoodDrinkCategory> FoodDrinkCategories
		{
			get
			{
				return this.GetTable<FoodDrinkCategory>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReservationDetail")]
	public partial class ReservationDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _ReservationDetailID;
		
		private short _RoomID;
		
		private short _ReservationID;
		
		private decimal _QuotedRate;
		
		private System.DateTime _CheckinDate;
		
		private byte _Nights;
		
		private char _Status;
		
		private string _Comments;
		
		private System.Nullable<short> _DiscountID;
		
		private byte _NumberOfAdults;
		
		private byte _NumberOfChildren;
		
		private EntitySet<ReservationDetailBilling> _ReservationDetailBillings;
		
		private EntityRef<Room> _Room;
		
		private EntityRef<Reservation> _Reservation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReservationDetailIDChanging(short value);
    partial void OnReservationDetailIDChanged();
    partial void OnRoomIDChanging(short value);
    partial void OnRoomIDChanged();
    partial void OnReservationIDChanging(short value);
    partial void OnReservationIDChanged();
    partial void OnQuotedRateChanging(decimal value);
    partial void OnQuotedRateChanged();
    partial void OnCheckinDateChanging(System.DateTime value);
    partial void OnCheckinDateChanged();
    partial void OnNightsChanging(byte value);
    partial void OnNightsChanged();
    partial void OnStatusChanging(char value);
    partial void OnStatusChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    partial void OnDiscountIDChanging(System.Nullable<short> value);
    partial void OnDiscountIDChanged();
    partial void OnNumberOfAdultsChanging(byte value);
    partial void OnNumberOfAdultsChanged();
    partial void OnNumberOfChildrenChanging(byte value);
    partial void OnNumberOfChildrenChanged();
    #endregion
		
		public ReservationDetail()
		{
			this._ReservationDetailBillings = new EntitySet<ReservationDetailBilling>(new Action<ReservationDetailBilling>(this.attach_ReservationDetailBillings), new Action<ReservationDetailBilling>(this.detach_ReservationDetailBillings));
			this._Room = default(EntityRef<Room>);
			this._Reservation = default(EntityRef<Reservation>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReservationDetailID", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short ReservationDetailID
		{
			get
			{
				return this._ReservationDetailID;
			}
			set
			{
				if ((this._ReservationDetailID != value))
				{
					this.OnReservationDetailIDChanging(value);
					this.SendPropertyChanging();
					this._ReservationDetailID = value;
					this.SendPropertyChanged("ReservationDetailID");
					this.OnReservationDetailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomID", DbType="SmallInt NOT NULL")]
		public short RoomID
		{
			get
			{
				return this._RoomID;
			}
			set
			{
				if ((this._RoomID != value))
				{
					if (this._Room.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRoomIDChanging(value);
					this.SendPropertyChanging();
					this._RoomID = value;
					this.SendPropertyChanged("RoomID");
					this.OnRoomIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReservationID", DbType="SmallInt NOT NULL")]
		public short ReservationID
		{
			get
			{
				return this._ReservationID;
			}
			set
			{
				if ((this._ReservationID != value))
				{
					if (this._Reservation.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnReservationIDChanging(value);
					this.SendPropertyChanging();
					this._ReservationID = value;
					this.SendPropertyChanged("ReservationID");
					this.OnReservationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuotedRate", DbType="SmallMoney NOT NULL")]
		public decimal QuotedRate
		{
			get
			{
				return this._QuotedRate;
			}
			set
			{
				if ((this._QuotedRate != value))
				{
					this.OnQuotedRateChanging(value);
					this.SendPropertyChanging();
					this._QuotedRate = value;
					this.SendPropertyChanged("QuotedRate");
					this.OnQuotedRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckinDate", DbType="SmallDateTime NOT NULL")]
		public System.DateTime CheckinDate
		{
			get
			{
				return this._CheckinDate;
			}
			set
			{
				if ((this._CheckinDate != value))
				{
					this.OnCheckinDateChanging(value);
					this.SendPropertyChanging();
					this._CheckinDate = value;
					this.SendPropertyChanged("CheckinDate");
					this.OnCheckinDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nights", DbType="TinyInt NOT NULL")]
		public byte Nights
		{
			get
			{
				return this._Nights;
			}
			set
			{
				if ((this._Nights != value))
				{
					this.OnNightsChanging(value);
					this.SendPropertyChanging();
					this._Nights = value;
					this.SendPropertyChanged("Nights");
					this.OnNightsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Char(1) NOT NULL")]
		public char Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="VarChar(MAX)")]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this.OnCommentsChanging(value);
					this.SendPropertyChanging();
					this._Comments = value;
					this.SendPropertyChanged("Comments");
					this.OnCommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiscountID", DbType="SmallInt")]
		public System.Nullable<short> DiscountID
		{
			get
			{
				return this._DiscountID;
			}
			set
			{
				if ((this._DiscountID != value))
				{
					this.OnDiscountIDChanging(value);
					this.SendPropertyChanging();
					this._DiscountID = value;
					this.SendPropertyChanged("DiscountID");
					this.OnDiscountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfAdults", DbType="TinyInt NOT NULL")]
		public byte NumberOfAdults
		{
			get
			{
				return this._NumberOfAdults;
			}
			set
			{
				if ((this._NumberOfAdults != value))
				{
					this.OnNumberOfAdultsChanging(value);
					this.SendPropertyChanging();
					this._NumberOfAdults = value;
					this.SendPropertyChanged("NumberOfAdults");
					this.OnNumberOfAdultsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfChildren", DbType="TinyInt NOT NULL")]
		public byte NumberOfChildren
		{
			get
			{
				return this._NumberOfChildren;
			}
			set
			{
				if ((this._NumberOfChildren != value))
				{
					this.OnNumberOfChildrenChanging(value);
					this.SendPropertyChanging();
					this._NumberOfChildren = value;
					this.SendPropertyChanged("NumberOfChildren");
					this.OnNumberOfChildrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ReservationDetail_ReservationDetailBilling", Storage="_ReservationDetailBillings", ThisKey="ReservationDetailID", OtherKey="ReservationDetailID")]
		public EntitySet<ReservationDetailBilling> ReservationDetailBillings
		{
			get
			{
				return this._ReservationDetailBillings;
			}
			set
			{
				this._ReservationDetailBillings.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Room_ReservationDetail", Storage="_Room", ThisKey="RoomID", OtherKey="RoomID", IsForeignKey=true)]
		public Room Room
		{
			get
			{
				return this._Room.Entity;
			}
			set
			{
				Room previousValue = this._Room.Entity;
				if (((previousValue != value) 
							|| (this._Room.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Room.Entity = null;
						previousValue.ReservationDetails.Remove(this);
					}
					this._Room.Entity = value;
					if ((value != null))
					{
						value.ReservationDetails.Add(this);
						this._RoomID = value.RoomID;
					}
					else
					{
						this._RoomID = default(short);
					}
					this.SendPropertyChanged("Room");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Reservation_ReservationDetail", Storage="_Reservation", ThisKey="ReservationID", OtherKey="ReservationID", IsForeignKey=true)]
		public Reservation Reservation
		{
			get
			{
				return this._Reservation.Entity;
			}
			set
			{
				Reservation previousValue = this._Reservation.Entity;
				if (((previousValue != value) 
							|| (this._Reservation.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Reservation.Entity = null;
						previousValue.ReservationDetails.Remove(this);
					}
					this._Reservation.Entity = value;
					if ((value != null))
					{
						value.ReservationDetails.Add(this);
						this._ReservationID = value.ReservationID;
					}
					else
					{
						this._ReservationID = default(short);
					}
					this.SendPropertyChanged("Reservation");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ReservationDetailBillings(ReservationDetailBilling entity)
		{
			this.SendPropertyChanging();
			entity.ReservationDetail = this;
		}
		
		private void detach_ReservationDetailBillings(ReservationDetailBilling entity)
		{
			this.SendPropertyChanging();
			entity.ReservationDetail = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Room")]
	public partial class Room : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _RoomID;
		
		private short _HotelRoomTypeID;
		
		private string _RoomNumbers;
		
		private string _RoomDescription;
		
		private bool _RoomSmoking;
		
		private string _RoomBedConfiguration;
		
		private bool _RoomHandicap;
		
		private char _RoomStatus;
		
		private EntitySet<ReservationDetail> _ReservationDetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoomIDChanging(short value);
    partial void OnRoomIDChanged();
    partial void OnHotelRoomTypeIDChanging(short value);
    partial void OnHotelRoomTypeIDChanged();
    partial void OnRoomNumbersChanging(string value);
    partial void OnRoomNumbersChanged();
    partial void OnRoomDescriptionChanging(string value);
    partial void OnRoomDescriptionChanged();
    partial void OnRoomSmokingChanging(bool value);
    partial void OnRoomSmokingChanged();
    partial void OnRoomBedConfigurationChanging(string value);
    partial void OnRoomBedConfigurationChanged();
    partial void OnRoomHandicapChanging(bool value);
    partial void OnRoomHandicapChanged();
    partial void OnRoomStatusChanging(char value);
    partial void OnRoomStatusChanged();
    #endregion
		
		public Room()
		{
			this._ReservationDetails = new EntitySet<ReservationDetail>(new Action<ReservationDetail>(this.attach_ReservationDetails), new Action<ReservationDetail>(this.detach_ReservationDetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomID", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short RoomID
		{
			get
			{
				return this._RoomID;
			}
			set
			{
				if ((this._RoomID != value))
				{
					this.OnRoomIDChanging(value);
					this.SendPropertyChanging();
					this._RoomID = value;
					this.SendPropertyChanged("RoomID");
					this.OnRoomIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HotelRoomTypeID", DbType="SmallInt NOT NULL")]
		public short HotelRoomTypeID
		{
			get
			{
				return this._HotelRoomTypeID;
			}
			set
			{
				if ((this._HotelRoomTypeID != value))
				{
					this.OnHotelRoomTypeIDChanging(value);
					this.SendPropertyChanging();
					this._HotelRoomTypeID = value;
					this.SendPropertyChanged("HotelRoomTypeID");
					this.OnHotelRoomTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomNumbers", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string RoomNumbers
		{
			get
			{
				return this._RoomNumbers;
			}
			set
			{
				if ((this._RoomNumbers != value))
				{
					this.OnRoomNumbersChanging(value);
					this.SendPropertyChanging();
					this._RoomNumbers = value;
					this.SendPropertyChanged("RoomNumbers");
					this.OnRoomNumbersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomDescription", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string RoomDescription
		{
			get
			{
				return this._RoomDescription;
			}
			set
			{
				if ((this._RoomDescription != value))
				{
					this.OnRoomDescriptionChanging(value);
					this.SendPropertyChanging();
					this._RoomDescription = value;
					this.SendPropertyChanged("RoomDescription");
					this.OnRoomDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomSmoking", DbType="Bit NOT NULL")]
		public bool RoomSmoking
		{
			get
			{
				return this._RoomSmoking;
			}
			set
			{
				if ((this._RoomSmoking != value))
				{
					this.OnRoomSmokingChanging(value);
					this.SendPropertyChanging();
					this._RoomSmoking = value;
					this.SendPropertyChanged("RoomSmoking");
					this.OnRoomSmokingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBedConfiguration", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string RoomBedConfiguration
		{
			get
			{
				return this._RoomBedConfiguration;
			}
			set
			{
				if ((this._RoomBedConfiguration != value))
				{
					this.OnRoomBedConfigurationChanging(value);
					this.SendPropertyChanging();
					this._RoomBedConfiguration = value;
					this.SendPropertyChanged("RoomBedConfiguration");
					this.OnRoomBedConfigurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomHandicap", DbType="Bit NOT NULL")]
		public bool RoomHandicap
		{
			get
			{
				return this._RoomHandicap;
			}
			set
			{
				if ((this._RoomHandicap != value))
				{
					this.OnRoomHandicapChanging(value);
					this.SendPropertyChanging();
					this._RoomHandicap = value;
					this.SendPropertyChanged("RoomHandicap");
					this.OnRoomHandicapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomStatus", DbType="Char(1) NOT NULL")]
		public char RoomStatus
		{
			get
			{
				return this._RoomStatus;
			}
			set
			{
				if ((this._RoomStatus != value))
				{
					this.OnRoomStatusChanging(value);
					this.SendPropertyChanging();
					this._RoomStatus = value;
					this.SendPropertyChanged("RoomStatus");
					this.OnRoomStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Room_ReservationDetail", Storage="_ReservationDetails", ThisKey="RoomID", OtherKey="RoomID")]
		public EntitySet<ReservationDetail> ReservationDetails
		{
			get
			{
				return this._ReservationDetails;
			}
			set
			{
				this._ReservationDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ReservationDetails(ReservationDetail entity)
		{
			this.SendPropertyChanging();
			entity.Room = this;
		}
		
		private void detach_ReservationDetails(ReservationDetail entity)
		{
			this.SendPropertyChanging();
			entity.Room = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reservation")]
	public partial class Reservation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _ReservationID;
		
		private short _GuestID;
		
		private System.DateTime _ReservationDate;
		
		private char _ReservationStatus;
		
		private string _ReservationComments;
		
		private EntitySet<ReservationDetail> _ReservationDetails;
		
		private EntityRef<Guest> _Guest;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReservationIDChanging(short value);
    partial void OnReservationIDChanged();
    partial void OnGuestIDChanging(short value);
    partial void OnGuestIDChanged();
    partial void OnReservationDateChanging(System.DateTime value);
    partial void OnReservationDateChanged();
    partial void OnReservationStatusChanging(char value);
    partial void OnReservationStatusChanged();
    partial void OnReservationCommentsChanging(string value);
    partial void OnReservationCommentsChanged();
    #endregion
		
		public Reservation()
		{
			this._ReservationDetails = new EntitySet<ReservationDetail>(new Action<ReservationDetail>(this.attach_ReservationDetails), new Action<ReservationDetail>(this.detach_ReservationDetails));
			this._Guest = default(EntityRef<Guest>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReservationID", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short ReservationID
		{
			get
			{
				return this._ReservationID;
			}
			set
			{
				if ((this._ReservationID != value))
				{
					this.OnReservationIDChanging(value);
					this.SendPropertyChanging();
					this._ReservationID = value;
					this.SendPropertyChanged("ReservationID");
					this.OnReservationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestID", DbType="SmallInt NOT NULL")]
		public short GuestID
		{
			get
			{
				return this._GuestID;
			}
			set
			{
				if ((this._GuestID != value))
				{
					if (this._Guest.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGuestIDChanging(value);
					this.SendPropertyChanging();
					this._GuestID = value;
					this.SendPropertyChanged("GuestID");
					this.OnGuestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReservationDate", DbType="SmallDateTime NOT NULL")]
		public System.DateTime ReservationDate
		{
			get
			{
				return this._ReservationDate;
			}
			set
			{
				if ((this._ReservationDate != value))
				{
					this.OnReservationDateChanging(value);
					this.SendPropertyChanging();
					this._ReservationDate = value;
					this.SendPropertyChanged("ReservationDate");
					this.OnReservationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReservationStatus", DbType="Char(1) NOT NULL")]
		public char ReservationStatus
		{
			get
			{
				return this._ReservationStatus;
			}
			set
			{
				if ((this._ReservationStatus != value))
				{
					this.OnReservationStatusChanging(value);
					this.SendPropertyChanging();
					this._ReservationStatus = value;
					this.SendPropertyChanged("ReservationStatus");
					this.OnReservationStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReservationComments", DbType="VarChar(200)")]
		public string ReservationComments
		{
			get
			{
				return this._ReservationComments;
			}
			set
			{
				if ((this._ReservationComments != value))
				{
					this.OnReservationCommentsChanging(value);
					this.SendPropertyChanging();
					this._ReservationComments = value;
					this.SendPropertyChanged("ReservationComments");
					this.OnReservationCommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Reservation_ReservationDetail", Storage="_ReservationDetails", ThisKey="ReservationID", OtherKey="ReservationID")]
		public EntitySet<ReservationDetail> ReservationDetails
		{
			get
			{
				return this._ReservationDetails;
			}
			set
			{
				this._ReservationDetails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Guest_Reservation", Storage="_Guest", ThisKey="GuestID", OtherKey="GuestID", IsForeignKey=true)]
		public Guest Guest
		{
			get
			{
				return this._Guest.Entity;
			}
			set
			{
				Guest previousValue = this._Guest.Entity;
				if (((previousValue != value) 
							|| (this._Guest.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Guest.Entity = null;
						previousValue.Reservations.Remove(this);
					}
					this._Guest.Entity = value;
					if ((value != null))
					{
						value.Reservations.Add(this);
						this._GuestID = value.GuestID;
					}
					else
					{
						this._GuestID = default(short);
					}
					this.SendPropertyChanged("Guest");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ReservationDetails(ReservationDetail entity)
		{
			this.SendPropertyChanging();
			entity.Reservation = this;
		}
		
		private void detach_ReservationDetails(ReservationDetail entity)
		{
			this.SendPropertyChanging();
			entity.Reservation = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Guest")]
	public partial class Guest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _GuestID;
		
		private string _GuestSalutation;
		
		private string _GuestFirstName;
		
		private string _GuestSurName;
		
		private string _GuestCompany;
		
		private string _GuestAddress;
		
		private string _GuestCity;
		
		private string _GuestRegion;
		
		private string _GuestPostalCode;
		
		private string _GuestCountry;
		
		private string _GuestFax;
		
		private string _GuestPhone;
		
		private string _GuestEmail;
		
		private string _GuestComments;
		
		private string _GuestIDNumber;
		
		private string _GuestIDIssueCountry;
		
		private string _GuestIDComment;
		
		private EntitySet<Reservation> _Reservations;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGuestIDChanging(short value);
    partial void OnGuestIDChanged();
    partial void OnGuestSalutationChanging(string value);
    partial void OnGuestSalutationChanged();
    partial void OnGuestFirstNameChanging(string value);
    partial void OnGuestFirstNameChanged();
    partial void OnGuestSurNameChanging(string value);
    partial void OnGuestSurNameChanged();
    partial void OnGuestCompanyChanging(string value);
    partial void OnGuestCompanyChanged();
    partial void OnGuestAddressChanging(string value);
    partial void OnGuestAddressChanged();
    partial void OnGuestCityChanging(string value);
    partial void OnGuestCityChanged();
    partial void OnGuestRegionChanging(string value);
    partial void OnGuestRegionChanged();
    partial void OnGuestPostalCodeChanging(string value);
    partial void OnGuestPostalCodeChanged();
    partial void OnGuestCountryChanging(string value);
    partial void OnGuestCountryChanged();
    partial void OnGuestFaxChanging(string value);
    partial void OnGuestFaxChanged();
    partial void OnGuestPhoneChanging(string value);
    partial void OnGuestPhoneChanged();
    partial void OnGuestEmailChanging(string value);
    partial void OnGuestEmailChanged();
    partial void OnGuestCommentsChanging(string value);
    partial void OnGuestCommentsChanged();
    partial void OnGuestIDNumberChanging(string value);
    partial void OnGuestIDNumberChanged();
    partial void OnGuestIDIssueCountryChanging(string value);
    partial void OnGuestIDIssueCountryChanged();
    partial void OnGuestIDCommentChanging(string value);
    partial void OnGuestIDCommentChanged();
    #endregion
		
		public Guest()
		{
			this._Reservations = new EntitySet<Reservation>(new Action<Reservation>(this.attach_Reservations), new Action<Reservation>(this.detach_Reservations));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestID", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short GuestID
		{
			get
			{
				return this._GuestID;
			}
			set
			{
				if ((this._GuestID != value))
				{
					this.OnGuestIDChanging(value);
					this.SendPropertyChanging();
					this._GuestID = value;
					this.SendPropertyChanged("GuestID");
					this.OnGuestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestSalutation", DbType="VarChar(5)")]
		public string GuestSalutation
		{
			get
			{
				return this._GuestSalutation;
			}
			set
			{
				if ((this._GuestSalutation != value))
				{
					this.OnGuestSalutationChanging(value);
					this.SendPropertyChanging();
					this._GuestSalutation = value;
					this.SendPropertyChanged("GuestSalutation");
					this.OnGuestSalutationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestFirstName", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string GuestFirstName
		{
			get
			{
				return this._GuestFirstName;
			}
			set
			{
				if ((this._GuestFirstName != value))
				{
					this.OnGuestFirstNameChanging(value);
					this.SendPropertyChanging();
					this._GuestFirstName = value;
					this.SendPropertyChanged("GuestFirstName");
					this.OnGuestFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestSurName", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string GuestSurName
		{
			get
			{
				return this._GuestSurName;
			}
			set
			{
				if ((this._GuestSurName != value))
				{
					this.OnGuestSurNameChanging(value);
					this.SendPropertyChanging();
					this._GuestSurName = value;
					this.SendPropertyChanged("GuestSurName");
					this.OnGuestSurNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestCompany", DbType="VarChar(50)")]
		public string GuestCompany
		{
			get
			{
				return this._GuestCompany;
			}
			set
			{
				if ((this._GuestCompany != value))
				{
					this.OnGuestCompanyChanging(value);
					this.SendPropertyChanging();
					this._GuestCompany = value;
					this.SendPropertyChanged("GuestCompany");
					this.OnGuestCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestAddress", DbType="VarChar(50)")]
		public string GuestAddress
		{
			get
			{
				return this._GuestAddress;
			}
			set
			{
				if ((this._GuestAddress != value))
				{
					this.OnGuestAddressChanging(value);
					this.SendPropertyChanging();
					this._GuestAddress = value;
					this.SendPropertyChanged("GuestAddress");
					this.OnGuestAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestCity", DbType="VarChar(50)")]
		public string GuestCity
		{
			get
			{
				return this._GuestCity;
			}
			set
			{
				if ((this._GuestCity != value))
				{
					this.OnGuestCityChanging(value);
					this.SendPropertyChanging();
					this._GuestCity = value;
					this.SendPropertyChanged("GuestCity");
					this.OnGuestCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestRegion", DbType="VarChar(50)")]
		public string GuestRegion
		{
			get
			{
				return this._GuestRegion;
			}
			set
			{
				if ((this._GuestRegion != value))
				{
					this.OnGuestRegionChanging(value);
					this.SendPropertyChanging();
					this._GuestRegion = value;
					this.SendPropertyChanged("GuestRegion");
					this.OnGuestRegionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestPostalCode", DbType="VarChar(50)")]
		public string GuestPostalCode
		{
			get
			{
				return this._GuestPostalCode;
			}
			set
			{
				if ((this._GuestPostalCode != value))
				{
					this.OnGuestPostalCodeChanging(value);
					this.SendPropertyChanging();
					this._GuestPostalCode = value;
					this.SendPropertyChanged("GuestPostalCode");
					this.OnGuestPostalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestCountry", DbType="VarChar(20)")]
		public string GuestCountry
		{
			get
			{
				return this._GuestCountry;
			}
			set
			{
				if ((this._GuestCountry != value))
				{
					this.OnGuestCountryChanging(value);
					this.SendPropertyChanging();
					this._GuestCountry = value;
					this.SendPropertyChanged("GuestCountry");
					this.OnGuestCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestFax", DbType="VarChar(20)")]
		public string GuestFax
		{
			get
			{
				return this._GuestFax;
			}
			set
			{
				if ((this._GuestFax != value))
				{
					this.OnGuestFaxChanging(value);
					this.SendPropertyChanging();
					this._GuestFax = value;
					this.SendPropertyChanged("GuestFax");
					this.OnGuestFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestPhone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string GuestPhone
		{
			get
			{
				return this._GuestPhone;
			}
			set
			{
				if ((this._GuestPhone != value))
				{
					this.OnGuestPhoneChanging(value);
					this.SendPropertyChanging();
					this._GuestPhone = value;
					this.SendPropertyChanged("GuestPhone");
					this.OnGuestPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestEmail", DbType="VarChar(30)")]
		public string GuestEmail
		{
			get
			{
				return this._GuestEmail;
			}
			set
			{
				if ((this._GuestEmail != value))
				{
					this.OnGuestEmailChanging(value);
					this.SendPropertyChanging();
					this._GuestEmail = value;
					this.SendPropertyChanged("GuestEmail");
					this.OnGuestEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestComments", DbType="VarChar(200)")]
		public string GuestComments
		{
			get
			{
				return this._GuestComments;
			}
			set
			{
				if ((this._GuestComments != value))
				{
					this.OnGuestCommentsChanging(value);
					this.SendPropertyChanging();
					this._GuestComments = value;
					this.SendPropertyChanged("GuestComments");
					this.OnGuestCommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestIDNumber", DbType="VarChar(50)")]
		public string GuestIDNumber
		{
			get
			{
				return this._GuestIDNumber;
			}
			set
			{
				if ((this._GuestIDNumber != value))
				{
					this.OnGuestIDNumberChanging(value);
					this.SendPropertyChanging();
					this._GuestIDNumber = value;
					this.SendPropertyChanged("GuestIDNumber");
					this.OnGuestIDNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestIDIssueCountry", DbType="VarChar(50)")]
		public string GuestIDIssueCountry
		{
			get
			{
				return this._GuestIDIssueCountry;
			}
			set
			{
				if ((this._GuestIDIssueCountry != value))
				{
					this.OnGuestIDIssueCountryChanging(value);
					this.SendPropertyChanging();
					this._GuestIDIssueCountry = value;
					this.SendPropertyChanged("GuestIDIssueCountry");
					this.OnGuestIDIssueCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestIDComment", DbType="VarChar(50)")]
		public string GuestIDComment
		{
			get
			{
				return this._GuestIDComment;
			}
			set
			{
				if ((this._GuestIDComment != value))
				{
					this.OnGuestIDCommentChanging(value);
					this.SendPropertyChanging();
					this._GuestIDComment = value;
					this.SendPropertyChanged("GuestIDComment");
					this.OnGuestIDCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Guest_Reservation", Storage="_Reservations", ThisKey="GuestID", OtherKey="GuestID")]
		public EntitySet<Reservation> Reservations
		{
			get
			{
				return this._Reservations;
			}
			set
			{
				this._Reservations.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Reservations(Reservation entity)
		{
			this.SendPropertyChanging();
			entity.Guest = this;
		}
		
		private void detach_Reservations(Reservation entity)
		{
			this.SendPropertyChanging();
			entity.Guest = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReservationDetailBilling")]
	public partial class ReservationDetailBilling : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _ReservationDetailBillingID;
		
		private System.Nullable<short> _ReservationDetailID;
		
		private short _BillingCategoryID;
		
		private string _BillingDescription;
		
		private decimal _BillingAmount;
		
		private byte _BillingItemQty;
		
		private System.DateTime _BillingItemDate;
		
		private string _Comments;
		
		private string _EmployeeID;
		
		private string _TransEmployee;
		
		private EntitySet<LineItem> _LineItems;
		
		private EntityRef<ReservationDetail> _ReservationDetail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReservationDetailBillingIDChanging(short value);
    partial void OnReservationDetailBillingIDChanged();
    partial void OnReservationDetailIDChanging(System.Nullable<short> value);
    partial void OnReservationDetailIDChanged();
    partial void OnBillingCategoryIDChanging(short value);
    partial void OnBillingCategoryIDChanged();
    partial void OnBillingDescriptionChanging(string value);
    partial void OnBillingDescriptionChanged();
    partial void OnBillingAmountChanging(decimal value);
    partial void OnBillingAmountChanged();
    partial void OnBillingItemQtyChanging(byte value);
    partial void OnBillingItemQtyChanged();
    partial void OnBillingItemDateChanging(System.DateTime value);
    partial void OnBillingItemDateChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    partial void OnEmployeeIDChanging(string value);
    partial void OnEmployeeIDChanged();
    partial void OnTransEmployeeChanging(string value);
    partial void OnTransEmployeeChanged();
    #endregion
		
		public ReservationDetailBilling()
		{
			this._LineItems = new EntitySet<LineItem>(new Action<LineItem>(this.attach_LineItems), new Action<LineItem>(this.detach_LineItems));
			this._ReservationDetail = default(EntityRef<ReservationDetail>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReservationDetailBillingID", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short ReservationDetailBillingID
		{
			get
			{
				return this._ReservationDetailBillingID;
			}
			set
			{
				if ((this._ReservationDetailBillingID != value))
				{
					this.OnReservationDetailBillingIDChanging(value);
					this.SendPropertyChanging();
					this._ReservationDetailBillingID = value;
					this.SendPropertyChanged("ReservationDetailBillingID");
					this.OnReservationDetailBillingIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReservationDetailID", DbType="SmallInt")]
		public System.Nullable<short> ReservationDetailID
		{
			get
			{
				return this._ReservationDetailID;
			}
			set
			{
				if ((this._ReservationDetailID != value))
				{
					if (this._ReservationDetail.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnReservationDetailIDChanging(value);
					this.SendPropertyChanging();
					this._ReservationDetailID = value;
					this.SendPropertyChanged("ReservationDetailID");
					this.OnReservationDetailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingCategoryID", DbType="SmallInt NOT NULL")]
		public short BillingCategoryID
		{
			get
			{
				return this._BillingCategoryID;
			}
			set
			{
				if ((this._BillingCategoryID != value))
				{
					this.OnBillingCategoryIDChanging(value);
					this.SendPropertyChanging();
					this._BillingCategoryID = value;
					this.SendPropertyChanged("BillingCategoryID");
					this.OnBillingCategoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingDescription", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BillingDescription
		{
			get
			{
				return this._BillingDescription;
			}
			set
			{
				if ((this._BillingDescription != value))
				{
					this.OnBillingDescriptionChanging(value);
					this.SendPropertyChanging();
					this._BillingDescription = value;
					this.SendPropertyChanged("BillingDescription");
					this.OnBillingDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingAmount", DbType="SmallMoney NOT NULL")]
		public decimal BillingAmount
		{
			get
			{
				return this._BillingAmount;
			}
			set
			{
				if ((this._BillingAmount != value))
				{
					this.OnBillingAmountChanging(value);
					this.SendPropertyChanging();
					this._BillingAmount = value;
					this.SendPropertyChanged("BillingAmount");
					this.OnBillingAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingItemQty", DbType="TinyInt NOT NULL")]
		public byte BillingItemQty
		{
			get
			{
				return this._BillingItemQty;
			}
			set
			{
				if ((this._BillingItemQty != value))
				{
					this.OnBillingItemQtyChanging(value);
					this.SendPropertyChanging();
					this._BillingItemQty = value;
					this.SendPropertyChanged("BillingItemQty");
					this.OnBillingItemQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingItemDate", DbType="SmallDateTime NOT NULL")]
		public System.DateTime BillingItemDate
		{
			get
			{
				return this._BillingItemDate;
			}
			set
			{
				if ((this._BillingItemDate != value))
				{
					this.OnBillingItemDateChanging(value);
					this.SendPropertyChanging();
					this._BillingItemDate = value;
					this.SendPropertyChanged("BillingItemDate");
					this.OnBillingItemDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="VarChar(200)")]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this.OnCommentsChanging(value);
					this.SendPropertyChanging();
					this._Comments = value;
					this.SendPropertyChanged("Comments");
					this.OnCommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="VarChar(20)")]
		public string EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					this.OnEmployeeIDChanging(value);
					this.SendPropertyChanging();
					this._EmployeeID = value;
					this.SendPropertyChanged("EmployeeID");
					this.OnEmployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransEmployee", DbType="VarChar(4)")]
		public string TransEmployee
		{
			get
			{
				return this._TransEmployee;
			}
			set
			{
				if ((this._TransEmployee != value))
				{
					this.OnTransEmployeeChanging(value);
					this.SendPropertyChanging();
					this._TransEmployee = value;
					this.SendPropertyChanged("TransEmployee");
					this.OnTransEmployeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ReservationDetailBilling_LineItem", Storage="_LineItems", ThisKey="ReservationDetailBillingID", OtherKey="ReservationDetailBillingID")]
		public EntitySet<LineItem> LineItems
		{
			get
			{
				return this._LineItems;
			}
			set
			{
				this._LineItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ReservationDetail_ReservationDetailBilling", Storage="_ReservationDetail", ThisKey="ReservationDetailID", OtherKey="ReservationDetailID", IsForeignKey=true)]
		public ReservationDetail ReservationDetail
		{
			get
			{
				return this._ReservationDetail.Entity;
			}
			set
			{
				ReservationDetail previousValue = this._ReservationDetail.Entity;
				if (((previousValue != value) 
							|| (this._ReservationDetail.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ReservationDetail.Entity = null;
						previousValue.ReservationDetailBillings.Remove(this);
					}
					this._ReservationDetail.Entity = value;
					if ((value != null))
					{
						value.ReservationDetailBillings.Add(this);
						this._ReservationDetailID = value.ReservationDetailID;
					}
					else
					{
						this._ReservationDetailID = default(Nullable<short>);
					}
					this.SendPropertyChanged("ReservationDetail");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LineItems(LineItem entity)
		{
			this.SendPropertyChanging();
			entity.ReservationDetailBilling = this;
		}
		
		private void detach_LineItems(LineItem entity)
		{
			this.SendPropertyChanging();
			entity.ReservationDetailBilling = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LineItem")]
	public partial class LineItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LineItemTransactionID;
		
		private short _ReservationDetailBillingID;
		
		private System.Nullable<short> _MenuItemID;
		
		private decimal _LineItemAmount;
		
		private EntityRef<ReservationDetailBilling> _ReservationDetailBilling;
		
		private EntityRef<MenuItem> _MenuItem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLineItemTransactionIDChanging(int value);
    partial void OnLineItemTransactionIDChanged();
    partial void OnReservationDetailBillingIDChanging(short value);
    partial void OnReservationDetailBillingIDChanged();
    partial void OnMenuItemIDChanging(System.Nullable<short> value);
    partial void OnMenuItemIDChanged();
    partial void OnLineItemAmountChanging(decimal value);
    partial void OnLineItemAmountChanged();
    #endregion
		
		public LineItem()
		{
			this._ReservationDetailBilling = default(EntityRef<ReservationDetailBilling>);
			this._MenuItem = default(EntityRef<MenuItem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineItemTransactionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LineItemTransactionID
		{
			get
			{
				return this._LineItemTransactionID;
			}
			set
			{
				if ((this._LineItemTransactionID != value))
				{
					this.OnLineItemTransactionIDChanging(value);
					this.SendPropertyChanging();
					this._LineItemTransactionID = value;
					this.SendPropertyChanged("LineItemTransactionID");
					this.OnLineItemTransactionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReservationDetailBillingID", DbType="SmallInt NOT NULL")]
		public short ReservationDetailBillingID
		{
			get
			{
				return this._ReservationDetailBillingID;
			}
			set
			{
				if ((this._ReservationDetailBillingID != value))
				{
					if (this._ReservationDetailBilling.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnReservationDetailBillingIDChanging(value);
					this.SendPropertyChanging();
					this._ReservationDetailBillingID = value;
					this.SendPropertyChanged("ReservationDetailBillingID");
					this.OnReservationDetailBillingIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuItemID", DbType="SmallInt")]
		public System.Nullable<short> MenuItemID
		{
			get
			{
				return this._MenuItemID;
			}
			set
			{
				if ((this._MenuItemID != value))
				{
					if (this._MenuItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMenuItemIDChanging(value);
					this.SendPropertyChanging();
					this._MenuItemID = value;
					this.SendPropertyChanged("MenuItemID");
					this.OnMenuItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineItemAmount", DbType="SmallMoney NOT NULL")]
		public decimal LineItemAmount
		{
			get
			{
				return this._LineItemAmount;
			}
			set
			{
				if ((this._LineItemAmount != value))
				{
					this.OnLineItemAmountChanging(value);
					this.SendPropertyChanging();
					this._LineItemAmount = value;
					this.SendPropertyChanged("LineItemAmount");
					this.OnLineItemAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ReservationDetailBilling_LineItem", Storage="_ReservationDetailBilling", ThisKey="ReservationDetailBillingID", OtherKey="ReservationDetailBillingID", IsForeignKey=true)]
		public ReservationDetailBilling ReservationDetailBilling
		{
			get
			{
				return this._ReservationDetailBilling.Entity;
			}
			set
			{
				ReservationDetailBilling previousValue = this._ReservationDetailBilling.Entity;
				if (((previousValue != value) 
							|| (this._ReservationDetailBilling.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ReservationDetailBilling.Entity = null;
						previousValue.LineItems.Remove(this);
					}
					this._ReservationDetailBilling.Entity = value;
					if ((value != null))
					{
						value.LineItems.Add(this);
						this._ReservationDetailBillingID = value.ReservationDetailBillingID;
					}
					else
					{
						this._ReservationDetailBillingID = default(short);
					}
					this.SendPropertyChanged("ReservationDetailBilling");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MenuItem_LineItem", Storage="_MenuItem", ThisKey="MenuItemID", OtherKey="MenuItemID", IsForeignKey=true)]
		public MenuItem MenuItem
		{
			get
			{
				return this._MenuItem.Entity;
			}
			set
			{
				MenuItem previousValue = this._MenuItem.Entity;
				if (((previousValue != value) 
							|| (this._MenuItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MenuItem.Entity = null;
						previousValue.LineItems.Remove(this);
					}
					this._MenuItem.Entity = value;
					if ((value != null))
					{
						value.LineItems.Add(this);
						this._MenuItemID = value.MenuItemID;
					}
					else
					{
						this._MenuItemID = default(Nullable<short>);
					}
					this.SendPropertyChanged("MenuItem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MenuItem")]
	public partial class MenuItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _MenuItemID;
		
		private short _FoodDrinkCategoryID;
		
		private string _MenuItemName;
		
		private decimal _MenuItemPrice;
		
		private EntitySet<LineItem> _LineItems;
		
		private EntitySet<MenuItemIngredient> _MenuItemIngredients;
		
		private EntityRef<FoodDrinkCategory> _FoodDrinkCategory;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMenuItemIDChanging(short value);
    partial void OnMenuItemIDChanged();
    partial void OnFoodDrinkCategoryIDChanging(short value);
    partial void OnFoodDrinkCategoryIDChanged();
    partial void OnMenuItemNameChanging(string value);
    partial void OnMenuItemNameChanged();
    partial void OnMenuItemPriceChanging(decimal value);
    partial void OnMenuItemPriceChanged();
    #endregion
		
		public MenuItem()
		{
			this._LineItems = new EntitySet<LineItem>(new Action<LineItem>(this.attach_LineItems), new Action<LineItem>(this.detach_LineItems));
			this._MenuItemIngredients = new EntitySet<MenuItemIngredient>(new Action<MenuItemIngredient>(this.attach_MenuItemIngredients), new Action<MenuItemIngredient>(this.detach_MenuItemIngredients));
			this._FoodDrinkCategory = default(EntityRef<FoodDrinkCategory>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuItemID", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short MenuItemID
		{
			get
			{
				return this._MenuItemID;
			}
			set
			{
				if ((this._MenuItemID != value))
				{
					this.OnMenuItemIDChanging(value);
					this.SendPropertyChanging();
					this._MenuItemID = value;
					this.SendPropertyChanged("MenuItemID");
					this.OnMenuItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoodDrinkCategoryID", DbType="SmallInt NOT NULL")]
		public short FoodDrinkCategoryID
		{
			get
			{
				return this._FoodDrinkCategoryID;
			}
			set
			{
				if ((this._FoodDrinkCategoryID != value))
				{
					if (this._FoodDrinkCategory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFoodDrinkCategoryIDChanging(value);
					this.SendPropertyChanging();
					this._FoodDrinkCategoryID = value;
					this.SendPropertyChanged("FoodDrinkCategoryID");
					this.OnFoodDrinkCategoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuItemName", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string MenuItemName
		{
			get
			{
				return this._MenuItemName;
			}
			set
			{
				if ((this._MenuItemName != value))
				{
					this.OnMenuItemNameChanging(value);
					this.SendPropertyChanging();
					this._MenuItemName = value;
					this.SendPropertyChanged("MenuItemName");
					this.OnMenuItemNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuItemPrice", DbType="SmallMoney NOT NULL")]
		public decimal MenuItemPrice
		{
			get
			{
				return this._MenuItemPrice;
			}
			set
			{
				if ((this._MenuItemPrice != value))
				{
					this.OnMenuItemPriceChanging(value);
					this.SendPropertyChanging();
					this._MenuItemPrice = value;
					this.SendPropertyChanged("MenuItemPrice");
					this.OnMenuItemPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MenuItem_LineItem", Storage="_LineItems", ThisKey="MenuItemID", OtherKey="MenuItemID")]
		public EntitySet<LineItem> LineItems
		{
			get
			{
				return this._LineItems;
			}
			set
			{
				this._LineItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MenuItem_MenuItemIngredient", Storage="_MenuItemIngredients", ThisKey="MenuItemID", OtherKey="MenuItemID")]
		public EntitySet<MenuItemIngredient> MenuItemIngredients
		{
			get
			{
				return this._MenuItemIngredients;
			}
			set
			{
				this._MenuItemIngredients.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FoodDrinkCategory_MenuItem", Storage="_FoodDrinkCategory", ThisKey="FoodDrinkCategoryID", OtherKey="FoodDrinkCategoryID", IsForeignKey=true)]
		public FoodDrinkCategory FoodDrinkCategory
		{
			get
			{
				return this._FoodDrinkCategory.Entity;
			}
			set
			{
				FoodDrinkCategory previousValue = this._FoodDrinkCategory.Entity;
				if (((previousValue != value) 
							|| (this._FoodDrinkCategory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FoodDrinkCategory.Entity = null;
						previousValue.MenuItems.Remove(this);
					}
					this._FoodDrinkCategory.Entity = value;
					if ((value != null))
					{
						value.MenuItems.Add(this);
						this._FoodDrinkCategoryID = value.FoodDrinkCategoryID;
					}
					else
					{
						this._FoodDrinkCategoryID = default(short);
					}
					this.SendPropertyChanged("FoodDrinkCategory");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LineItems(LineItem entity)
		{
			this.SendPropertyChanging();
			entity.MenuItem = this;
		}
		
		private void detach_LineItems(LineItem entity)
		{
			this.SendPropertyChanging();
			entity.MenuItem = null;
		}
		
		private void attach_MenuItemIngredients(MenuItemIngredient entity)
		{
			this.SendPropertyChanging();
			entity.MenuItem = this;
		}
		
		private void detach_MenuItemIngredients(MenuItemIngredient entity)
		{
			this.SendPropertyChanging();
			entity.MenuItem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MenuItemIngredient")]
	public partial class MenuItemIngredient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _MenuItemIngredientID;
		
		private short _MenuItemID;
		
		private short _IngredientID;
		
		private decimal _MenuItemIngredientQty;
		
		private EntityRef<MenuItem> _MenuItem;
		
		private EntityRef<Ingredient> _Ingredient;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMenuItemIngredientIDChanging(short value);
    partial void OnMenuItemIngredientIDChanged();
    partial void OnMenuItemIDChanging(short value);
    partial void OnMenuItemIDChanged();
    partial void OnIngredientIDChanging(short value);
    partial void OnIngredientIDChanged();
    partial void OnMenuItemIngredientQtyChanging(decimal value);
    partial void OnMenuItemIngredientQtyChanged();
    #endregion
		
		public MenuItemIngredient()
		{
			this._MenuItem = default(EntityRef<MenuItem>);
			this._Ingredient = default(EntityRef<Ingredient>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuItemIngredientID", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short MenuItemIngredientID
		{
			get
			{
				return this._MenuItemIngredientID;
			}
			set
			{
				if ((this._MenuItemIngredientID != value))
				{
					this.OnMenuItemIngredientIDChanging(value);
					this.SendPropertyChanging();
					this._MenuItemIngredientID = value;
					this.SendPropertyChanged("MenuItemIngredientID");
					this.OnMenuItemIngredientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuItemID", DbType="SmallInt NOT NULL")]
		public short MenuItemID
		{
			get
			{
				return this._MenuItemID;
			}
			set
			{
				if ((this._MenuItemID != value))
				{
					if (this._MenuItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMenuItemIDChanging(value);
					this.SendPropertyChanging();
					this._MenuItemID = value;
					this.SendPropertyChanged("MenuItemID");
					this.OnMenuItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IngredientID", DbType="SmallInt NOT NULL")]
		public short IngredientID
		{
			get
			{
				return this._IngredientID;
			}
			set
			{
				if ((this._IngredientID != value))
				{
					if (this._Ingredient.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIngredientIDChanging(value);
					this.SendPropertyChanging();
					this._IngredientID = value;
					this.SendPropertyChanged("IngredientID");
					this.OnIngredientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuItemIngredientQty", DbType="Decimal(18,0) NOT NULL")]
		public decimal MenuItemIngredientQty
		{
			get
			{
				return this._MenuItemIngredientQty;
			}
			set
			{
				if ((this._MenuItemIngredientQty != value))
				{
					this.OnMenuItemIngredientQtyChanging(value);
					this.SendPropertyChanging();
					this._MenuItemIngredientQty = value;
					this.SendPropertyChanged("MenuItemIngredientQty");
					this.OnMenuItemIngredientQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MenuItem_MenuItemIngredient", Storage="_MenuItem", ThisKey="MenuItemID", OtherKey="MenuItemID", IsForeignKey=true)]
		public MenuItem MenuItem
		{
			get
			{
				return this._MenuItem.Entity;
			}
			set
			{
				MenuItem previousValue = this._MenuItem.Entity;
				if (((previousValue != value) 
							|| (this._MenuItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MenuItem.Entity = null;
						previousValue.MenuItemIngredients.Remove(this);
					}
					this._MenuItem.Entity = value;
					if ((value != null))
					{
						value.MenuItemIngredients.Add(this);
						this._MenuItemID = value.MenuItemID;
					}
					else
					{
						this._MenuItemID = default(short);
					}
					this.SendPropertyChanged("MenuItem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ingredient_MenuItemIngredient", Storage="_Ingredient", ThisKey="IngredientID", OtherKey="IngredientID", IsForeignKey=true)]
		public Ingredient Ingredient
		{
			get
			{
				return this._Ingredient.Entity;
			}
			set
			{
				Ingredient previousValue = this._Ingredient.Entity;
				if (((previousValue != value) 
							|| (this._Ingredient.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ingredient.Entity = null;
						previousValue.MenuItemIngredients.Remove(this);
					}
					this._Ingredient.Entity = value;
					if ((value != null))
					{
						value.MenuItemIngredients.Add(this);
						this._IngredientID = value.IngredientID;
					}
					else
					{
						this._IngredientID = default(short);
					}
					this.SendPropertyChanged("Ingredient");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ingredient")]
	public partial class Ingredient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _IngredientID;
		
		private string _IngredientName;
		
		private string _IngredientDescription;
		
		private EntitySet<MenuItemIngredient> _MenuItemIngredients;
		
		private EntitySet<IngredientPurchaseHistory> _IngredientPurchaseHistories;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIngredientIDChanging(short value);
    partial void OnIngredientIDChanged();
    partial void OnIngredientNameChanging(string value);
    partial void OnIngredientNameChanged();
    partial void OnIngredientDescriptionChanging(string value);
    partial void OnIngredientDescriptionChanged();
    #endregion
		
		public Ingredient()
		{
			this._MenuItemIngredients = new EntitySet<MenuItemIngredient>(new Action<MenuItemIngredient>(this.attach_MenuItemIngredients), new Action<MenuItemIngredient>(this.detach_MenuItemIngredients));
			this._IngredientPurchaseHistories = new EntitySet<IngredientPurchaseHistory>(new Action<IngredientPurchaseHistory>(this.attach_IngredientPurchaseHistories), new Action<IngredientPurchaseHistory>(this.detach_IngredientPurchaseHistories));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IngredientID", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short IngredientID
		{
			get
			{
				return this._IngredientID;
			}
			set
			{
				if ((this._IngredientID != value))
				{
					this.OnIngredientIDChanging(value);
					this.SendPropertyChanging();
					this._IngredientID = value;
					this.SendPropertyChanged("IngredientID");
					this.OnIngredientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IngredientName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string IngredientName
		{
			get
			{
				return this._IngredientName;
			}
			set
			{
				if ((this._IngredientName != value))
				{
					this.OnIngredientNameChanging(value);
					this.SendPropertyChanging();
					this._IngredientName = value;
					this.SendPropertyChanged("IngredientName");
					this.OnIngredientNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IngredientDescription", DbType="VarChar(MAX)")]
		public string IngredientDescription
		{
			get
			{
				return this._IngredientDescription;
			}
			set
			{
				if ((this._IngredientDescription != value))
				{
					this.OnIngredientDescriptionChanging(value);
					this.SendPropertyChanging();
					this._IngredientDescription = value;
					this.SendPropertyChanged("IngredientDescription");
					this.OnIngredientDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ingredient_MenuItemIngredient", Storage="_MenuItemIngredients", ThisKey="IngredientID", OtherKey="IngredientID")]
		public EntitySet<MenuItemIngredient> MenuItemIngredients
		{
			get
			{
				return this._MenuItemIngredients;
			}
			set
			{
				this._MenuItemIngredients.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ingredient_IngredientPurchaseHistory", Storage="_IngredientPurchaseHistories", ThisKey="IngredientID", OtherKey="IngredientID")]
		public EntitySet<IngredientPurchaseHistory> IngredientPurchaseHistories
		{
			get
			{
				return this._IngredientPurchaseHistories;
			}
			set
			{
				this._IngredientPurchaseHistories.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MenuItemIngredients(MenuItemIngredient entity)
		{
			this.SendPropertyChanging();
			entity.Ingredient = this;
		}
		
		private void detach_MenuItemIngredients(MenuItemIngredient entity)
		{
			this.SendPropertyChanging();
			entity.Ingredient = null;
		}
		
		private void attach_IngredientPurchaseHistories(IngredientPurchaseHistory entity)
		{
			this.SendPropertyChanging();
			entity.Ingredient = this;
		}
		
		private void detach_IngredientPurchaseHistories(IngredientPurchaseHistory entity)
		{
			this.SendPropertyChanging();
			entity.Ingredient = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IngredientPurchase")]
	public partial class IngredientPurchase : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _PurchaseID;
		
		private System.DateTime _PurchaseDate;
		
		private EntitySet<IngredientPurchaseHistory> _IngredientPurchaseHistories;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPurchaseIDChanging(short value);
    partial void OnPurchaseIDChanged();
    partial void OnPurchaseDateChanging(System.DateTime value);
    partial void OnPurchaseDateChanged();
    #endregion
		
		public IngredientPurchase()
		{
			this._IngredientPurchaseHistories = new EntitySet<IngredientPurchaseHistory>(new Action<IngredientPurchaseHistory>(this.attach_IngredientPurchaseHistories), new Action<IngredientPurchaseHistory>(this.detach_IngredientPurchaseHistories));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurchaseID", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short PurchaseID
		{
			get
			{
				return this._PurchaseID;
			}
			set
			{
				if ((this._PurchaseID != value))
				{
					this.OnPurchaseIDChanging(value);
					this.SendPropertyChanging();
					this._PurchaseID = value;
					this.SendPropertyChanged("PurchaseID");
					this.OnPurchaseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurchaseDate", DbType="SmallDateTime NOT NULL")]
		public System.DateTime PurchaseDate
		{
			get
			{
				return this._PurchaseDate;
			}
			set
			{
				if ((this._PurchaseDate != value))
				{
					this.OnPurchaseDateChanging(value);
					this.SendPropertyChanging();
					this._PurchaseDate = value;
					this.SendPropertyChanged("PurchaseDate");
					this.OnPurchaseDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="IngredientPurchase_IngredientPurchaseHistory", Storage="_IngredientPurchaseHistories", ThisKey="PurchaseID", OtherKey="PurchaseID")]
		public EntitySet<IngredientPurchaseHistory> IngredientPurchaseHistories
		{
			get
			{
				return this._IngredientPurchaseHistories;
			}
			set
			{
				this._IngredientPurchaseHistories.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_IngredientPurchaseHistories(IngredientPurchaseHistory entity)
		{
			this.SendPropertyChanging();
			entity.IngredientPurchase = this;
		}
		
		private void detach_IngredientPurchaseHistories(IngredientPurchaseHistory entity)
		{
			this.SendPropertyChanging();
			entity.IngredientPurchase = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IngredientPurchaseHistory")]
	public partial class IngredientPurchaseHistory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _IngredientPurchaseHistoryID;
		
		private short _IngredientID;
		
		private short _PurchaseID;
		
		private decimal _IngredientPurchaseHistoryPrice;
		
		private short _IngredientPurchaseHistoryQty;
		
		private EntityRef<Ingredient> _Ingredient;
		
		private EntityRef<IngredientPurchase> _IngredientPurchase;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIngredientPurchaseHistoryIDChanging(short value);
    partial void OnIngredientPurchaseHistoryIDChanged();
    partial void OnIngredientIDChanging(short value);
    partial void OnIngredientIDChanged();
    partial void OnPurchaseIDChanging(short value);
    partial void OnPurchaseIDChanged();
    partial void OnIngredientPurchaseHistoryPriceChanging(decimal value);
    partial void OnIngredientPurchaseHistoryPriceChanged();
    partial void OnIngredientPurchaseHistoryQtyChanging(short value);
    partial void OnIngredientPurchaseHistoryQtyChanged();
    #endregion
		
		public IngredientPurchaseHistory()
		{
			this._Ingredient = default(EntityRef<Ingredient>);
			this._IngredientPurchase = default(EntityRef<IngredientPurchase>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IngredientPurchaseHistoryID", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short IngredientPurchaseHistoryID
		{
			get
			{
				return this._IngredientPurchaseHistoryID;
			}
			set
			{
				if ((this._IngredientPurchaseHistoryID != value))
				{
					this.OnIngredientPurchaseHistoryIDChanging(value);
					this.SendPropertyChanging();
					this._IngredientPurchaseHistoryID = value;
					this.SendPropertyChanged("IngredientPurchaseHistoryID");
					this.OnIngredientPurchaseHistoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IngredientID", DbType="SmallInt NOT NULL")]
		public short IngredientID
		{
			get
			{
				return this._IngredientID;
			}
			set
			{
				if ((this._IngredientID != value))
				{
					if (this._Ingredient.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIngredientIDChanging(value);
					this.SendPropertyChanging();
					this._IngredientID = value;
					this.SendPropertyChanged("IngredientID");
					this.OnIngredientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurchaseID", DbType="SmallInt NOT NULL")]
		public short PurchaseID
		{
			get
			{
				return this._PurchaseID;
			}
			set
			{
				if ((this._PurchaseID != value))
				{
					if (this._IngredientPurchase.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPurchaseIDChanging(value);
					this.SendPropertyChanging();
					this._PurchaseID = value;
					this.SendPropertyChanged("PurchaseID");
					this.OnPurchaseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IngredientPurchaseHistoryPrice", DbType="SmallMoney NOT NULL")]
		public decimal IngredientPurchaseHistoryPrice
		{
			get
			{
				return this._IngredientPurchaseHistoryPrice;
			}
			set
			{
				if ((this._IngredientPurchaseHistoryPrice != value))
				{
					this.OnIngredientPurchaseHistoryPriceChanging(value);
					this.SendPropertyChanging();
					this._IngredientPurchaseHistoryPrice = value;
					this.SendPropertyChanged("IngredientPurchaseHistoryPrice");
					this.OnIngredientPurchaseHistoryPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IngredientPurchaseHistoryQty", DbType="SmallInt NOT NULL")]
		public short IngredientPurchaseHistoryQty
		{
			get
			{
				return this._IngredientPurchaseHistoryQty;
			}
			set
			{
				if ((this._IngredientPurchaseHistoryQty != value))
				{
					this.OnIngredientPurchaseHistoryQtyChanging(value);
					this.SendPropertyChanging();
					this._IngredientPurchaseHistoryQty = value;
					this.SendPropertyChanged("IngredientPurchaseHistoryQty");
					this.OnIngredientPurchaseHistoryQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ingredient_IngredientPurchaseHistory", Storage="_Ingredient", ThisKey="IngredientID", OtherKey="IngredientID", IsForeignKey=true)]
		public Ingredient Ingredient
		{
			get
			{
				return this._Ingredient.Entity;
			}
			set
			{
				Ingredient previousValue = this._Ingredient.Entity;
				if (((previousValue != value) 
							|| (this._Ingredient.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ingredient.Entity = null;
						previousValue.IngredientPurchaseHistories.Remove(this);
					}
					this._Ingredient.Entity = value;
					if ((value != null))
					{
						value.IngredientPurchaseHistories.Add(this);
						this._IngredientID = value.IngredientID;
					}
					else
					{
						this._IngredientID = default(short);
					}
					this.SendPropertyChanged("Ingredient");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="IngredientPurchase_IngredientPurchaseHistory", Storage="_IngredientPurchase", ThisKey="PurchaseID", OtherKey="PurchaseID", IsForeignKey=true)]
		public IngredientPurchase IngredientPurchase
		{
			get
			{
				return this._IngredientPurchase.Entity;
			}
			set
			{
				IngredientPurchase previousValue = this._IngredientPurchase.Entity;
				if (((previousValue != value) 
							|| (this._IngredientPurchase.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._IngredientPurchase.Entity = null;
						previousValue.IngredientPurchaseHistories.Remove(this);
					}
					this._IngredientPurchase.Entity = value;
					if ((value != null))
					{
						value.IngredientPurchaseHistories.Add(this);
						this._PurchaseID = value.PurchaseID;
					}
					else
					{
						this._PurchaseID = default(short);
					}
					this.SendPropertyChanged("IngredientPurchase");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FoodDrinkCategory")]
	public partial class FoodDrinkCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _FoodDrinkCategoryID;
		
		private string _FoodDrinkCategoryName;
		
		private string _FoodDrinkCategoryTypeID;
		
		private EntitySet<MenuItem> _MenuItems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFoodDrinkCategoryIDChanging(short value);
    partial void OnFoodDrinkCategoryIDChanged();
    partial void OnFoodDrinkCategoryNameChanging(string value);
    partial void OnFoodDrinkCategoryNameChanged();
    partial void OnFoodDrinkCategoryTypeIDChanging(string value);
    partial void OnFoodDrinkCategoryTypeIDChanged();
    #endregion
		
		public FoodDrinkCategory()
		{
			this._MenuItems = new EntitySet<MenuItem>(new Action<MenuItem>(this.attach_MenuItems), new Action<MenuItem>(this.detach_MenuItems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoodDrinkCategoryID", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short FoodDrinkCategoryID
		{
			get
			{
				return this._FoodDrinkCategoryID;
			}
			set
			{
				if ((this._FoodDrinkCategoryID != value))
				{
					this.OnFoodDrinkCategoryIDChanging(value);
					this.SendPropertyChanging();
					this._FoodDrinkCategoryID = value;
					this.SendPropertyChanged("FoodDrinkCategoryID");
					this.OnFoodDrinkCategoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoodDrinkCategoryName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string FoodDrinkCategoryName
		{
			get
			{
				return this._FoodDrinkCategoryName;
			}
			set
			{
				if ((this._FoodDrinkCategoryName != value))
				{
					this.OnFoodDrinkCategoryNameChanging(value);
					this.SendPropertyChanging();
					this._FoodDrinkCategoryName = value;
					this.SendPropertyChanged("FoodDrinkCategoryName");
					this.OnFoodDrinkCategoryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoodDrinkCategoryTypeID", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string FoodDrinkCategoryTypeID
		{
			get
			{
				return this._FoodDrinkCategoryTypeID;
			}
			set
			{
				if ((this._FoodDrinkCategoryTypeID != value))
				{
					this.OnFoodDrinkCategoryTypeIDChanging(value);
					this.SendPropertyChanging();
					this._FoodDrinkCategoryTypeID = value;
					this.SendPropertyChanged("FoodDrinkCategoryTypeID");
					this.OnFoodDrinkCategoryTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FoodDrinkCategory_MenuItem", Storage="_MenuItems", ThisKey="FoodDrinkCategoryID", OtherKey="FoodDrinkCategoryID")]
		public EntitySet<MenuItem> MenuItems
		{
			get
			{
				return this._MenuItems;
			}
			set
			{
				this._MenuItems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MenuItems(MenuItem entity)
		{
			this.SendPropertyChanging();
			entity.FoodDrinkCategory = this;
		}
		
		private void detach_MenuItems(MenuItem entity)
		{
			this.SendPropertyChanging();
			entity.FoodDrinkCategory = null;
		}
	}
}
#pragma warning restore 1591
